### ISSUE TITLE
Crashing client when loading a world

### ISSUE THREAD

**Issue by YumatanGames** [mrmelon54/armored-elytra-fabric#13] opened 2022-06-29 12:53 UTC
Hi. I just installed the mod on my client and it causes my client to crash whenever I'm joying a server or single player world. 
At first I thought it was because I already have an armored elytra equipped in my server, so I've tried creating a completely new world and it still crashed before joining. 

Here's the latest log: https://paste.ee/p/Hm41V

Please, let me know if I can provide you with more info. :D

**Comment by mrmelon54** [comment] 2022-06-29 18:43
If you try with just armored elytra does the game crash?
Maybe its just your specific combination of mods?
Try removing one mod at a time (or other faster methods) to figure out which combination of mods causes the issue...

**Comment by YumatanGames** [comment] 2022-06-29 20:44
I was hoping the log would give a clue about which mod is conflicting... I didn't had time to do the mod testing yet, will try to do it as soon as I can.

**Comment by mrmelon54** [comment] 2022-06-29 21:22
I says `at net.minecraft.class_970.handler$doo000$selectArmorModel(class_970.java:3069)`
which could suggest armored elytra but it doesn't touch that method at all.. so it's highly unlikely
also armored elytra checks to see what armor you are wearing and thus an empty inventory wouldn't run any other code..
it also doesn't say armored elytra is specifically responsible for the crash just where the crash occured
try asking in the fabric discord as they maybe able to help..
but trying to slowly add/remove mods until you get a crash would help diagnose which mod actually causes the issue.

**Comment by mrmelon54** [comment] 2022-07-12 00:24
The issue is probably an incompatibility with another mod... can you try finding out which mod it is and get back to me

**Comment by mrmelon54** [comment] 2022-08-08 21:08
As there have been no replies for 28 days.. I am closing this issue.. feel free to reopen it..

**Closed as completed by mrmelon54** 2022-08-08 21:08 UTC
